DELETE FROM cms_values WHERE idclient= '<!--{client_id}-->' AND group_name='cfg_client';
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'path', '', '', '', '<!--{cms_path}-->projektXX/', 100, 'setuse_path', 'setuse_pathes', 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'htmlpath', '', '', '', '<!--{cms_full_http_path}-->projektXX/', 101, 'setuse_html_path', NULL, 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'contentfile', '', '', '', 'index.php', 102, 'setuse_contentfile', NULL, 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'space', '', '', '', '<!--{cms_full_http_path}-->projektXX/cms/img/space.gif', 105, 'setuse_space', NULL, 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'session_enabled', '', '', '', '1', 201, 'set_session_frontend_enabled', 'setuse_general', 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'session_lifetime', '', '', '', '15', 202, 'set_session_frontend_lifetime', '', 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'publish', '', '', '', '0', 203, 'setuse_publish', NULL, 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'edit_mode', '', '', '', '0', 204, 'setuse_edit_mode', NULL, 'txt', NULL, NULL, '0');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'wysiwyg_applet', '', '', '', '1', 205, 'setuse_wysiwyg_applet', NULL, 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'default_layout', '', '', '', '<html>\r\n<head>\r\n<cms:lay type="head"/>\r\n</head>\r\n<body>\r\n<cms:lay type="container" id="1" title="Seiten-Content"/>\r\n\r\n<cms:lay type="config"/>\r\n<cms:lay type="foot"/>\r\n</body>\r\n</html>', 206, 'setuse_default_layout', NULL, 'txtarea', NULL, NULL, 1);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'url_rewrite', '', '', '', '0', 207, 'setuse_url_rewrite', NULL, 'txt', NULL, NULL, 1);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'manipulate_output', '', '', '', 'echo $output;', 208, 'setuse_manipulate_output', NULL, 'txtarea', NULL, NULL, 1);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'errorpage', '', '', '', '0', 209, 'setuse_errorpage', NULL, 'txt', NULL, NULL, 1);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'loginpage', '', '', '', '0', 210, 'setuse_loginpage', NULL, 'txt', NULL, NULL, 1);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'cache', '', '', '', '1', 211, 'setuse_cache', NULL, 'txt', NULL, NULL, 1);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'upl_path', '', '', '', '<!--{cms_path}-->projektXX/media/', 300, 'setuse_upl_path', 'setuse_filemanager', 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'upl_htmlpath', '', '', '', '<!--{cms_full_http_path}-->projektXX/media/', 301, 'setuse_upl_htmlpath', NULL, 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'upl_forbidden', '', '', '', 'php, htaccess, htpasswd, css, js', 302, 'setuse_forbidden', NULL, 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'thumb_size', '', '', '', '100', 303, 'setuse_thumb_size', '', 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'thumb_aspectratio', '', '', '', '1', 304, 'setuse_thumb_aspectratio', '', 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'thumbext', '', '', '', '_cms_thumb', 305, 'setuse_thumb_ext', '', 'txt', NULL, NULL, 1);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'fm_delete_ignore_404', '', '', '', '1', 306, 'setuse_fm_delete_ignore_404', '', 'txt', NULL, NULL, 1);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'upl_addon', '', '', '', 'gif,jpg,jpeg,png', 310, 'setuse_upl_addon', '', 'txt', '', '', '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'remove_files_404', '', '', '', '1', 315, 'setuse_remove_files_404', '', 'txt', '', '', '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'remove_empty_directories', '', '', '', '0', 316, 'setuse_remove_empty_directories', '', 'txt', '', '', 1);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'css_sort_original', '', '', '', '0', 400, 'setuse_css_sort_original', 'setuse_css', 'txt', '', '', '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'css_checking', '', '', '', '1', 405, 'setuse_csschecking', '', 'txt', NULL, NULL, 1);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'css_ignore_rules_with_errors', '', '', '', '0', 410, 'setuse_css_ignore_error_rules', '', 'txt', NULL, NULL, 1);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'meta_description', '', '', '', '', 600, 'set_meta_description', 'set_meta', 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'meta_keywords', '', '', '', '', 601, 'set_meta_keywords', '', 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'meta_robots', '', '', '', 'index, follow', 602, 'set_meta_robots', '', 'txt', NULL, NULL, '1');
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'max_count_scandir', '', '', '', '10', 0, '', '', 'txt', NULL, NULL, 0);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'extend_time_scandir', '', '', '', '60', 0, '', '', 'txt', NULL, NULL, 0);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'max_count_scanfile', '', '', '', '2', 0, '', '', 'txt', NULL, NULL, 0);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'max_count_scanthumb', '', '', '', '10', 0, '', '', 'txt', NULL, NULL, 0);
INSERT INTO cms_values VALUES ('', <!--{client_id}-->, 0, 'cfg_client', 'session_frontend_domain', '', '', '', '.<!--{cms_cookie_domain}-->', 212, 'setuse_session_frontend_domain', NULL, 'txt', NULL, NULL, '1');
